services:
  ms-church-backend:
    build:
      context: ./cms
    restart: always
    volumes:
      - ./cms:/var/www/html
    ports:
      - 80:80
    networks:
      - ms-church-network
    environment:
      - KIRBY_HEADLESS_API_TOKEN=test

  ms-church-frontend:
    image: node:lts
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ['sh', './start.sh']
    networks:
      - ms-church-network
    environment:
      - KIRBY_API_TOKEN=test
      - KIRBY_BASE_URL=http://ms-church-backend

networks:
  ms-church-network:
    driver: bridge