services:
  ms-church-backend:
    build:
      context: ./cms
    restart: always
    volumes:
      - ./cms:/var/www/html
    ports:
      - 80:80
    networks:
      - ms-church-network
    environment:
      BACKEND_URL: http://ms-church-backend/cms
      FRONTEND_URL: http://localhost/cms
    pull_policy: build

  ms-church-frontend:
    image: node:lts
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev
    networks:
      - ms-church-network

networks:
  ms-church-network:
    driver: bridge