services:
  ms-church-backend:
    build:
      context: ./cms
    restart: always
    volumes:
      - ./cms:/var/www/html
    ports:
      - 80:80
    networks:
      - ms-church-network
    env_file: ./cms/.env

  ms-church-frontend:
    image: node:lts
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ['sh', './start.sh']
    networks:
      - ms-church-network

networks:
  ms-church-network:
    driver: bridge