services:
  ms-church-backend:
    build:
      context: ./cms
    restart: always
    volumes:
      - ms-church-backend:/var/www/html
    networks:
      - ms-church-network
      - nginx-network

  ms-church-frontend:
    build:
      context: ./frontend
    restart: always
    volumes:
      - ms-church-frontend:/src
    networks:
      - ms-church-network
      - nginx-network

networks:
  ms-church-network:
    driver: bridge
  nginx-network:
    external: true

volumes:
  ms-church-backend:
  ms-church-frontend: