services:
  ms-church-backend:
    build:
      context: ./cms
    restart: always
    volumes:
      - ms-church-backend:/var/www/html
    ports:
      - 80:80
    networks:
      - ms-church-network

  ms-church-frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ms-church-frontend:/src
    networks:
      - ms-church-network

networks:
  ms-church-network:
    driver: bridge

volumes:
  ms-church-backend:
  ms-church-frontend: