services:
  ms-church-backend:
    build:
      context: ./cms
    restart: always
    volumes:
      - ./cms:/var/www/html
    ports:
      - 80:80
    networks:
      - ms-church-network
    pull_policy: build

  ms-church-frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./frontend:/src
    pull_policy: build
    environment:
      HOST: 0.0.0.0
    networks:
      - ms-church-network

networks:
  ms-church-network:
    driver: bridge