services:
  ms-church-backend:
    build:
      context: ./cms
    restart: always
    ports:
      - 80
    volumes:
      - content:/var/www/html/content
      - accounts:/var/www/html/site/accounts
    networks:
      - ms-church-network
      - nginx-network

  ms-church-frontend:
    build:
      context: ./frontend
    restart: always
    ports: 
    - 3000
    networks:
      - ms-church-network
      - nginx-network

networks:
  ms-church-network:
    driver: bridge
  nginx-network:
    external: true

volumes:
  content:
  accounts: